name: Test DeepSeek API Key
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Validate API Key
        run: |
          echo "Workflow is now properly configured!"
          echo "Key exists: ${{ secrets.DEEPSEEK_API_KEY != '' }}"
