name: Test DeepSeek API Key
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Validate API Key
        run: |
          echo "If you see this, the workflow works!"
